# Numpy
* Numerical Python or numeric python
* numpy is a programming language that deals with multi-dimensional arrays and matrices
* numpy supports large number of mathematical operations


# why use numpy
* numpy is memory efficiency, meaning 
* especially for matrix multiplication and reshaping
* on top of that,Numpy is fast. in fact, TensorFlow and Scikit

In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.19.2


In [1]:
import numpy as np
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [6]:
data=np.array([[2,4,6,8],[2,5,6,0]])
print(data)

[[2 4 6 8]
 [2 5 6 0]]


In [7]:
a1=np.array([2,4,6,8])
a2=np.array([3,5,7,9])
print(a1+a2)
print(a1-a2)

[ 5  9 13 17]
[-1 -1 -1 -1]


In [10]:
data=np.array([[2,4,6,8],[2,5,6,0]])
print(np.shape(data))
print(data.dtype)

(2, 4)
int32


In [11]:
data=np.array([[2,4,6,8,9],[2,5,6,0]])
print(np.shape(data))


(2,)
object


<ipython-input-11-a1b0cb0e96be>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  data=np.array([[2,4,6,8,9],[2,5,6,0]])


In [12]:
data=np.array([[2.0,4.7,6.0,8.9],[2.9,5.6,6.0,9.7]])
print(np.shape(data))
print(data.dtype)

(2, 4)
float64


In [14]:
np.zeros((3,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.zeros((3,2),dtype=str)

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [17]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [18]:
data2=np.array([[1,2,3,4],[6,7,8,9]])
print(data2)
data2.reshape(4,2)

[[1 2 3 4]
 [6 7 8 9]]


array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [20]:
data2=np.array([[1,2,3,4],[6,7,8,9]])
print(data2)
data2.flatten()

[[1 2 3 4]
 [6 7 8 9]]


array([1, 2, 3, 4, 6, 7, 8, 9])

In [23]:
print(a1)
print(a2)
np.hstack((a1,a2))

[2 4 6 8]
[3 5 7 9]


array([2, 4, 6, 8, 3, 5, 7, 9])

In [27]:
print(a1)
print(a2)
np.vstack((a1))

[2 4 6 8]
[3 5 7 9]


array([[2],
       [4],
       [6],
       [8]])

In [33]:
data2=np.array([[1,1,2,3,4],[6,6,7,8,9]])
print(data2.sum())
print(data2.mean())
print(data2.std())#standard deviation
print(np.median(data2))
print(np.mod(1,2))

47
4.7
2.758622844826744
5.0
1


In [34]:
np.random.normal(5,4,10)

array([ 4.05486158,  8.0349373 ,  9.40226349,  8.60069904,  4.44352215,
        3.01327947,  8.27564215, 11.5671318 ,  0.12881708,  0.73503399])

In [36]:
data.min()

2.0

In [37]:
data.mean()

5.725

In [38]:
data.max()

9.7

In [39]:
data.T

array([[2. , 2.9],
       [4.7, 5.6],
       [6. , 6. ],
       [8.9, 9.7]])